### ISSUE TITLE
Could not pass event CreatureSpawnEvent to MobLimiter

### ISSUE THREAD

**Issue by Martynus** [CoreNetwork/MobLimiter#28]
I've recently been getting the following error. I'm not sure what caused it, I did update my Spigot to the latest build recently so I'm betting that has something to do with it.

The error:

````
[22:59:32 ERROR]: Could not pass event CreatureSpawnEvent to MobLimiter v3.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:275) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at net.minecraft.server.v1_8_R1.World.addEntity(World.java:1014) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.spawn(CraftWorld.java:1097) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.spawn(CraftWorld.java:837) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.CraftWorld.spawnEntity(CraftWorld.java:376) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at com.garbagemule.MobArena.waves.MACreature.spawn(MACreature.java:105) [MobArena.jar:?]
        at com.garbagemule.MobArena.MASpawnThread.spawnWave(MASpawnThread.java:165) [MobArena.jar:?]
        at com.garbagemule.MobArena.MASpawnThread.run(MASpawnThread.java:117) [MobArena.jar:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between world_nether and world
        at org.bukkit.Location.distanceSquared(Location.java:461) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at org.bukkit.Location.distance(Location.java:444) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
        at us.corenetwork.moblimiter.CreatureUtil.getSpawnDistanceLimitStatus(CreatureUtil.java:131) ~[?:?]
        at us.corenetwork.moblimiter.MobLimiterListener.onCreatureSpawn(MobLimiterListener.java:56) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_31]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_31]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:301) ~[spigot.jar:git-Spigot-6ee12f6-33d5de3]
        ... 18 more
````

**Comment by riddle** [comment]
Hey, thanks for the report. Can you try to replicate it for us, to make it easier to debug?

**Comment by matejdro** [comment]
Was this bug one-time thing or is it happening often?

**Comment by Martynus** [comment]
Oops sorry for the late reply. I haven't had this error anymore since I built a new Spigot. I saw more bug reports of other plugins having this issue with one of the later versions, but (I think) [this](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/spigot/commits/262d940478730387c77cc97c354bd99a342d9bb4) patch fixed it.
